version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/app/
    networks:
      - app
    container_name: app

  db:
    image: mysql:8.0.28
    cap_add:
      - SYS_NICE
    networks:
      - app
    container_name: dataBase

networks:
  app:
    driver: bridge